"""Payslip PDF rendering (spec B8).

WeasyPrint runs in the Linux container rather than on Windows, where it
needs GTK. If it is unavailable for any reason the payslip still renders as
standalone HTML rather than failing outright - a demo that shows the payslip
in a browser tab beats one that 500s at the last step.
"""
from __future__ import annotations

import logging
from decimal import Decimal

from jinja2 import Environment, select_autoescape
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.enums import RuleCategory
from app.models.payroll import Payslip

logger = logging.getLogger("paypulse.pdf")

_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><title>Payslip</title><style>
  @page { size: A4; margin: 18mm; }
  body { font-family: "DejaVu Sans", Helvetica, Arial, sans-serif;
         font-size: 11px; color: #1a1a1a; }
  h1 { font-size: 18px; margin: 0 0 2px; }
  .muted { color: #666; }
  .head { border-bottom: 2px solid #1a1a1a; padding-bottom: 8px;
          margin-bottom: 14px; }
  table { width: 100%; border-collapse: collapse; }
  .meta td { padding: 3px 0; vertical-align: top; }
  .meta .label { color: #666; width: 26%; }
  .lines { margin-top: 14px; }
  .lines th { text-align: left; border-bottom: 1px solid #999;
     padding: 6px 4px; font-size: 10px; text-transform: uppercase;
     letter-spacing: .04em; }
  .lines td { padding: 5px 4px; border-bottom: 1px solid #eee; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .subtotal td { font-weight: bold; border-top: 1px solid #999;
                 border-bottom: 2px solid #999; }
  .net td { font-weight: bold; font-size: 14px; border-top: 2px solid #1a1a1a;
            border-bottom: 3px double #1a1a1a; padding: 9px 4px; }
  .basis { margin-top: 16px; background: #f7f7f7; padding: 9px; }
  .basis td { padding: 2px 8px 2px 0; }
  footer { margin-top: 20px; font-size: 9px; color: #777;
           border-top: 1px solid #ddd; padding-top: 7px; }
</style></head><body>
  <div class="head">
    <h1>{{ company }}</h1>
    <div class="muted">Payslip for {{ period_label }}</div>
  </div>

  <table class="meta">
    <tr><td class="label">Employee</td><td><strong>{{ employee }}</strong></td>
        <td class="label">Pay Run</td><td>{{ payrun }}</td></tr>
    <tr><td class="label">Department</td><td>{{ department or '-' }}</td>
        <td class="label">Structure</td><td>{{ structure or '-' }}</td></tr>
    <tr><td class="label">Position</td><td>{{ position or '-' }}</td>
        <td class="label">Status</td><td>{{ state }}</td></tr>
    <tr><td class="label">Worked Days</td>
        <td>{{ payable_days }} of {{ period_days }}</td>
        <td class="label">Currency</td><td>{{ currency }}</td></tr>
  </table>

  <table class="lines">
    <thead><tr><th style="width:12%">Code</th><th>Description</th>
      <th style="width:14%">Category</th><th class="num" style="width:18%">Amount</th>
    </tr></thead>
    <tbody>
    {% for line in earnings %}
      <tr><td>{{ line.rule_code }}</td><td>{{ line.name }}</td>
          <td class="muted">{{ line.category.value }}</td>
          <td class="num">{{ money(line.amount) }}</td></tr>
    {% endfor %}
      <tr class="subtotal"><td colspan="3">Gross Salary</td>
          <td class="num">{{ money(gross) }}</td></tr>
    {% for line in deductions %}
      <tr><td>{{ line.rule_code }}</td><td>{{ line.name }}</td>
          <td class="muted">DEDUCTION</td>
          <td class="num">-{{ money(line.amount) }}</td></tr>
    {% endfor %}
      <tr class="subtotal"><td colspan="3">Total Deductions</td>
          <td class="num">-{{ money(total_deductions) }}</td></tr>
      <tr class="net"><td colspan="3">Net Salary</td>
          <td class="num">{{ currency }} {{ money(net) }}</td></tr>
    </tbody>
  </table>

  <table class="basis">
    <tr><td class="muted">Scheduled days</td><td>{{ period_days }}</td>
        <td class="muted">Days on contract</td><td>{{ contract_days }}</td>
        <td class="muted">Paid leave</td><td>{{ paid_leave_days }}</td></tr>
    <tr><td class="muted">Payable days</td><td>{{ payable_days }}</td>
        <td class="muted">Unpaid leave</td><td>{{ unpaid_leave_days }}</td>
        <td class="muted">Absent</td><td>{{ absent_days }}</td></tr>
    <tr><td class="muted">Hours worked</td><td>{{ worked_hours }}</td>
        <td class="muted">Overtime hours</td><td>{{ overtime_hours }}</td>
        <td></td><td></td></tr>
  </table>

  <footer>
    Confidential - this payslip contains personal salary information.
    Income Tax shown is a simplified estimate, not a statutory computation.
    Generated by {{ app_name }}.
  </footer>
</body></html>"""


def _money(value: Decimal) -> str:
    """Indian digit grouping: 12,34,567.89."""
    quantized = Decimal(value).quantize(Decimal("0.01"))
    negative = quantized < 0
    whole, _, frac = f"{abs(quantized):.2f}".partition(".")
    if len(whole) > 3:
        head, tail = whole[:-3], whole[-3:]
        parts = []
        while len(head) > 2:
            parts.insert(0, head[-2:])
            head = head[:-2]
        if head:
            parts.insert(0, head)
        whole = ",".join(parts + [tail])
    return f"{'-' if negative else ''}{whole}.{frac}"


def render_html(db: Session, payslip: Payslip) -> str:
    employee = payslip.employee
    earnings = [
        line
        for line in payslip.lines
        if line.category in (RuleCategory.BASIC, RuleCategory.ALLOWANCE)
    ]
    deductions = [
        line for line in payslip.lines if line.category is RuleCategory.DEDUCTION
    ]

    env = Environment(autoescape=select_autoescape(["html"]))
    template = env.from_string(_TEMPLATE)
    return template.render(
        company=settings.COMPANY_NAME,
        app_name=settings.APP_NAME,
        employee=employee.full_name if employee else f"#{payslip.employee_id}",
        department=(
            employee.department.name if employee and employee.department else None
        ),
        position=(
            employee.job_position.name if employee and employee.job_position else None
        ),
        payrun=payslip.payrun.name if payslip.payrun else "-",
        structure=(
            payslip.payrun.salary_structure.name
            if payslip.payrun and payslip.payrun.salary_structure
            else None
        ),
        period_label=(
            f"{payslip.period_start:%d %b %Y} to {payslip.period_end:%d %b %Y}"
        ),
        state=payslip.state.value,
        currency=payslip.currency,
        earnings=earnings,
        deductions=deductions,
        gross=payslip.gross,
        total_deductions=payslip.total_deductions,
        net=payslip.net,
        period_days=payslip.period_days,
        contract_days=payslip.contract_days,
        payable_days=payslip.payable_days,
        paid_leave_days=payslip.paid_leave_days,
        unpaid_leave_days=payslip.unpaid_leave_days,
        absent_days=payslip.absent_days,
        worked_hours=payslip.worked_hours,
        overtime_hours=payslip.overtime_hours,
        money=_money,
    )


def render_payslip(db: Session, payslip: Payslip) -> tuple[bytes, str, str]:
    """Return (content, media_type, extension).

    Falls back to HTML if WeasyPrint is missing, so the demo never dies at
    the last step of the flow.
    """
    html = render_html(db, payslip)
    try:
        from weasyprint import HTML  # imported lazily: heavy, and optional

        return HTML(string=html).write_pdf(), "application/pdf", "pdf"
    except Exception as exc:  # pragma: no cover - depends on the image
        logger.warning("WeasyPrint unavailable (%s); serving HTML instead", exc)
        return html.encode("utf-8"), "text/html; charset=utf-8", "html"
